# -*- coding: utf-8 -*-
"""final_tubes_deep-learning_kel-7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18mCO9KxQjSrU5--b6jKSj9TGpasmeG67
"""

!pip install -U transformers accelerate evaluate jiwer

!pip install bitsandbytes

!pip install datasets==3.6.0

import torch
import re
import evaluate
from dataclasses import dataclass
from typing import Any, Dict, List, Union
from datasets import load_dataset, concatenate_datasets, Audio
from transformers import (
    AutoProcessor,
    WhisperForConditionalGeneration,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer
)

# 1. SETTINGS & MODEL ID
model_id = "openai/whisper-base"
selected_langs = ['jav', 'sun', 'ind']

# 2. DATA LOADING
def load_multi_lang_ds(lang_list):
    all_ds = []
    for lang in lang_list:
        try:
            d = load_dataset("indonesian-nlp/librivox-indonesia", lang, split="train", trust_remote_code=True)
            d = d.map(lambda x: {"language": lang})
            all_ds.append(d)
        except Exception as e:
            print(f"Error loading {lang}: {e}")
    return concatenate_datasets(all_ds).shuffle(seed=42)

ds = load_multi_lang_ds(selected_langs)
ds = ds.cast_column("audio", Audio(sampling_rate=16_000))

# 3. PROCESSOR & PREPARATION
processor = AutoProcessor.from_pretrained(model_id)

def prepare_dataset(batch):
    audio = batch["audio"]
    # Extract features
    batch["input_features"] = processor(audio["array"], sampling_rate=16_000).input_features[0]

    # Clean text (Optional: remove regex part if you want to keep punctuation)
    chars_to_ignore_regex = r'[,\?\.\!\-\;\:\"\“\%\‘\”\[\]]'
    text = batch.get("sentence", "")
    clean_text = re.sub(chars_to_ignore_regex, '', text).lower()

    # Tokenize labels
    batch["labels"] = processor(text=clean_text).input_ids
    return batch

ds_processed = ds.map(prepare_dataset, remove_columns=ds.column_names, num_proc=1)
ds_split = ds_processed.train_test_split(test_size=0.2)

# 4. DATA COLLATOR CLASS
@dataclass
class DataCollatorSpeechSeq2SeqWithPadding:
    processor: Any
    def __call__(self, features: List[Dict[str, Union[List[int], torch.Tensor]]]) -> Dict[str, torch.Tensor]:
        input_features = [{"input_features": f["input_features"]} for f in features]
        batch = self.processor.feature_extractor.pad(input_features, return_tensors="pt")

        label_features = [{"input_ids": f["labels"]} for f in features]
        labels_batch = self.processor.tokenizer.pad(label_features, return_tensors="pt")
        labels = labels_batch["input_ids"].masked_fill(labels_batch.attention_mask.ne(1), -100)

        batch["labels"] = labels
        return batch

data_collator = DataCollatorSpeechSeq2SeqWithPadding(processor=processor)

# 5. METRICS
metric = evaluate.load("wer")

def compute_metrics(pred):
    pred_ids = pred.predictions
    label_ids = pred.label_ids
    label_ids[label_ids == -100] = processor.tokenizer.pad_token_id

    pred_str = processor.batch_decode(pred_ids, skip_special_tokens=True)
    label_str = processor.batch_decode(label_ids, skip_special_tokens=True)

    wer = 100 * metric.compute(predictions=pred_str, references=label_str)
    return {"wer": wer}

# 6. MODEL & TRAINING ARGUMENTS
model = WhisperForConditionalGeneration.from_pretrained(model_id)

# Force the model to use the correct language/task during generation
model.config.forced_decoder_ids = None
model.config.suppress_tokens = []

training_args = Seq2SeqTrainingArguments(
    output_dir="./whisper-small-multi-id",
    per_device_train_batch_size=8,
    gradient_accumulation_steps=2,
    learning_rate=5e-5,
    warmup_steps=100,
    num_train_epochs=5,
    eval_strategy="epoch",
    save_strategy="epoch",
    gradient_checkpointing=True,
    fp16=True,
    predict_with_generate=True,
    generation_max_length=225,
    logging_steps=25,
    report_to="none",
    load_best_model_at_end=True,
    metric_for_best_model="wer",
    greater_is_better=False,
    optim="adamw_bnb_8bit"
)

# 7. TRAIN
trainer = Seq2SeqTrainer(
    args=training_args,
    model=model,
    train_dataset=ds_split["train"],
    eval_dataset=ds_split["test"],
    data_collator=data_collator,
    compute_metrics=compute_metrics,
    processing_class=processor.feature_extractor,
)

print("Memulai Training...")
trainer.train()

# 8. SAVE
trainer.save_model("./whisper-id-final")
processor.save_pretrained("./whisper-id-final")
print("Model and Processor aman tersimpan!")

# Switch model to evaluation mode and move to GPU
model.eval()
model.to("cuda") # or device

print("--- Hasil Testing Model ---")

# Using the first 5 samples from the original dataset (or ds_split['test'])
for i in range(5):
    sample = ds[i]

    # Pre-process audio
    input_features = processor(
        sample["audio"]["array"],
        sampling_rate=16000,
        return_tensors="pt"
    ).input_features.to("cuda")

    # Generate with no_grad to save VRAM
    with torch.no_grad():
        predicted_ids = model.generate(
            input_features,
            # Force the model to start with the correct language token
            language="indonesian",
            task="transcribe"
        )

    # Decode
    transcription = processor.batch_decode(predicted_ids, skip_special_tokens=True)[0]

    print(f"\n[Sample {i}]")
    print(f"Actual   : {sample['sentence']}")
    print(f"Predicted: {transcription}")